# Generated by Django 5.0.14 on 2026-06-11 10:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VPNPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("total_gb", models.PositiveIntegerField()),
                ("duration_days", models.PositiveIntegerField()),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Used for safe soft-deletes to preserve historical metrics.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "VPN Plan",
                "verbose_name_plural": "VPN Plans",
            },
        ),
        migrations.CreateModel(
            name="ProxySubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "xui_client_uuid",
                    models.CharField(
                        help_text="Core downstream token used for client authentication across panels.",
                        max_length=36,
                    ),
                ),
                ("subscription_url", models.URLField()),
                ("total_allocated_gb", models.PositiveIntegerField()),
                (
                    "used_gb",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("last_known_up_bytes", models.BigIntegerField(default=0)),
                ("last_known_down_bytes", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WALLET_TOPUP", "Wallet Top-up"),
                            ("PLAN_PURCHASE", "Plan Purchase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "screenshot",
                    models.ImageField(upload_to="protected_media/transactions/"),
                ),
                (
                    "payment_ref_code",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Reference code must be uppercase alphanumeric characters only.",
                                regex="^[A-Z0-9]+$",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionConfigMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "xui_client_email",
                    models.CharField(
                        help_text="Automated unique email routing key required by remote XUI panels.",
                        max_length=255,
                    ),
                ),
                (
                    "inbound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapped_subscriptions",
                        to="billing_engine.xuiinbound",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="billing_engine.proxysubscription",
                    ),
                ),
            ],
            options={
                "unique_together": {("subscription", "inbound")},
            },
        ),
    ]
